# Generated by Django 6.0.5 on 2026-05-19 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_type', models.CharField(choices=[('full', 'Full Regression'), ('partial', 'Partial (selected endpoints)')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('selected_endpoints', models.JSONField(blank=True, default=list)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='test_results/')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('result_summary', models.JSONField(blank=True, default=dict)),
            ],
        ),
    ]
