# Generated by Django 6.0.5 on 2026-05-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WikiVisitCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('unique_visits', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
